name: BackPack
version: 1.16.0
api-version: 1.16
main: de.redoxcraft.backpack.main.Main
author: RedoxCraft
description: none
website: https://www.youtube.com/redoxcraft

commands:
   rucksack:
      description: Oeffnet deinen Rucksack